config/routes.rb
Rails.application.routes.draw do

  root to: 'topics#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "kaobooks" =>'kaobooks#index'

  get "topics" =>'topics#index'

  resources :topics do
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :content, presence: true
  belongs_to :user
  belongs_to :topic
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    # ログインユーザーに紐付けてインスタンス生成するためbuildメソッドを使用します。
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic

    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: 'コメントを投稿しました。' }
        format.json { render :show, status: :created, location: @comment }
        # JS形式でレスポンスを返します。
        format.js { render :index }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @comment.user_id == current_user.id
      if @comment.update(comment_params)
        redirect_to topic_path(@comment.topic)
      else
        render :edit
      end
    else
      redirect_to root_path, notice: "不正な操作が行われました！"
    end
  end
  
  def destroy
    if @comment.user_id == current_user.id
      @comment.destroy
      
      #redirect_to blogs_path, notice: "ブログを削除しました！"
      respond_to do |format|
        format.js { render :index }
      end
    else 
      redirect_to root_path, notice: "不正な操作が行われました！"
    end
  end

  def set_comment
    @comment = current_user.comments.find(params[:id])
  end

  private
    def comment_params
      params.require(:comment).permit(:topic_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic,comment], remote: true) do |f| %>
  <%= f.hidden_field :topic_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit "コメントする", class: "btn btn-sm btn-primary" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '編集', edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '削除', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="container">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
		<h1>コメント編集</h1>
		  <%= form_for(@comment, url: topic_comment_path(@comment.topic, @comment)) do |f| %>
		    <%= f.text_area :content, class: "form-control", placeholder: 'コメントを入力' %>
		    <br>
		    <%= f.submit 'コメントを送信', class: 'btn btn-sm btn-primary' %>
		<% end %>
	</div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')