config/routes.rb
Rails.application.routes.draw do

  root to: 'topics#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "kaobooks" =>'kaobooks#index'

  get "topics" =>'topics#index'

  resources :topics do
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	validates :content, presence: true

	#アソシエーション
	belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
	before_action :set_topic, only:[:show, :edit, :update, :destroy]

  def index
  	@topic = Topic.new
  	@topics = friend_topics
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end

  def new
  	@topic = Topic.new(topic_params)
  end

  def create
  	@topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
  	if @topic.save
  		redirect_to root_path, notice: "投稿しました！"
    else
      redirect_to root_path, notice: "投稿が失敗しました！"
  	end
  end

  def edit
  end

  def update
    if @topic.user_id == current_user.id
      if @topic.update(topic_params)
        redirect_to root_path, notice: "更新しました！"
      else
        redirect_to root_path, notice: "投稿が失敗しました！"
      end
    else
      redirect_to root_path, notice: "不正な操作が行われました！"
    end
  end

  def destroy
    if @topic.user_id == current_user.id
      @topic.destroy
      redirect_to root_path, notice: "削除しました！"
    else 
      redirect_to root_path, notice: "不正な操作が行われました！"
    end
  end

  private
	  def topic_params
	  	params.require(:topic).permit(:content)
	  end

	  def set_topic
	  	@topic = Topic.find(params[:id])
	  end

    def friend_topics
      topics = Topic.all.order(created_at: :desc)
      friends = current_user.friend
      timeline = []

      
      topics.each do |topic|
        timeline << topic if topic.user_id == current_user.id
        if friends.present?
          friends.each do |fri|
            timeline << topic if topic.user_id == fri.id
          end
        end
      end

      return timeline
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<div class="container">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
		<%= form_for(@topic) do |f| %>
			<%= f.text_field :content, class: "form-control" %>
			<br>
			<%= f.submit '更新する', class: 'btn btn-sm btn-primary'  %>
		<% end %>
	</div>
</div>

app/views/topics/index.html.erb
<div class="container">
	<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
		<h3><%# notice %></h3>


		<%= form_for(@topic, :html => {:class => 'form'}) do |f| %>
			<%= f.error_messages! %>
			<%= f.text_area :content, class: "form-control" %>
			<br>
			<%= f.submit "投稿する", class: 'btn btn-sm btn-success' %>
		<% end %>

		<% @topics.each do |topic| %>
			<div class="row">

				<div class="panel panel-default">
					<div class="panel-heading">
						<p>
							<%= profile_img(topic.user) %>
							<%= topic.user.name %>（<%= topic.created_at %>に投稿しました）
						</p>
					</div>

					<div class="panel-body">
						<%= topic.content %>
					</div>
					<div class="panel-footer">
						<% if topic.user_id == current_user.id %>
				      <%= link_to "編集", edit_topic_path(topic.id), class: 'btn btn-sm btn-success' %>
				      <%= link_to '削除', topic_path(topic.id), method: :delete, data: {confirm: "本当に削除していいですか？?"}, class: 'btn btn-sm btn-danger' %>
			      <% end %>
			      <%= link_to "詳細", topic_path(topic.id), class: 'btn btn-sm btn-default' %>
			    </div>
	      </div>
			</div>
		<% end %>
	</div>
</div>

app/views/topics/show.html.erb
<div class="container">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

	  <div class="panel panel-default">
	  	<div class="panel-heading">
				<p>
					<%= profile_img(@topic.user) %>
					<%= @topic.user.name %>（<%= @topic.created_at %>に投稿しました）
				</p>
			</div>
			<div class="panel-body">
				<p><%= @topic.content %></p>
			</div>
		</div>

		<h3>コメント一覧</h3>
	  <div class="panel panel-default">
	  	<div class="panel-heading">
			  <div id="comments_area">
			    <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
			  </div>
			</div>
		</div>
	  <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
	</div>
</div>