config/routes.rb
Rails.application.routes.draw do

  root to: 'topics#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "kaobooks" =>'kaobooks#index'

  get "topics" =>'topics#index'

  resources :topics do
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kaobook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<header>
	

	<nav class="navbar navbar-default">
		<div class="container-fluid">
	  	<div class="navbar-header">
		  	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span> 
	      </button>
	      <a class="navbar-brand" href="<%= root_path %>">
	        <%= image_tag('kaobook.png', { :border => '0', :alt => '新規登録', :width => "150"}) %>
	      </a>
	    </div>
	    <div class="collapse navbar-collapse" id="myNavbar">
	      <% if user_signed_in? %>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to 'マイページ', edit_user_registration_path %></li>
					  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
						<li><%= link_to 'ユーザー一覧', users_path %></li>
						<li><%= link_to "メッセージ", conversations_path %></li>
					</ul>
				<% end %>
			</div>
		</div>
	</nav>

	<% if false %>
	<%= link_to image_tag('kaobook.png', { :border => '0', :alt => '新規登録', :width => "200"}), root_path %>
	<% if user_signed_in? %>
		<ul>
			<li><%= link_to 'マイページ', edit_user_registration_path %></li>
		  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
			<li><%= link_to 'ユーザー一覧', users_path %></li>
			<li><%= link_to "メッセージ", conversations_path %></li>
		</ul>
	<% else %>
		<% if false %>
	  <li><%= link_to 'ログイン', new_user_session_path  %></li>
	  <li><%= link_to 'サインアップ', new_user_registration_path %></li>
	  <% end %>
	<% end %>
	<% end %>

</header>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>